### ISSUE TITLE
FIRST plugin fails on latest IDA Version 7.0.171130 Windows x64

### ISSUE THREAD

**Issue by hunterbr72** [vrtadmin/FIRST#7]
FIRST crashes with the latest IDA version 7.0.171130

Traceback (most recent call last):
File "C:/Program Files/IDA 7.0/plugins/first.py", line 3412, in ev_auto_queue_empty
return self.auto_queue_empty(arg, before7=False)
File "C:/Program Files/IDA 7.0/plugins/first.py", line 3455, in auto_queue_empty
return super(self.class, self).ev_auto_queue_empty(arg)
File "C:\Program Files\IDA 7.0\python\ida_ida.py", line 770, in __wrapper
rc = do_call(cb, *args)
File "C:\Program Files\IDA 7.0\python\ida_idp.py", line 2389, in __call_IDP_Hooks_auto_queue_empty
old_rc = cb(qtype)
File "C:/Program Files/IDA 7.0/plugins/first.py", line 3454, in auto_queue_empty
return super(self.class, self).auto_queue_empty(arg)
AttributeError: 'super' object has no attribute 'auto_queue_empty'
Exception in IDP Hook function: SWIG director method error. Error detected when calling 'IDP_Hooks.ev_auto_queue_empty'
Traceback (most recent call last):
File "C:/Program Files/IDA 7.0/plugins/first.py", line 3412, in ev_auto_queue_empty
return self.auto_queue_empty(arg, before7=False)
File "C:/Program Files/IDA 7.0/plugins/first.py", line 3455, in auto_queue_empty
return super(self.class, self).ev_auto_queue_empty(arg)
File "C:\Program Files\IDA 7.0\python\ida_ida.py", line 770, in __wrapper
rc = do_call(cb, *args)
File "C:\Program Files\IDA 7.0\python\ida_idp.py", line 2389, in __call_IDP_Hooks_auto_queue_empty
old_rc = cb(qtype)
File "C:/Program Files/IDA 7.0/plugins/first.py", line 3454, in auto_queue_empty
return super(self.class, self).auto_queue_empty(arg)
AttributeError: 'super' object has no attribute 'auto_queue_empty'
Exception in IDP Hook function: SWIG director method error. Error detected when calling 'IDP_Hooks.ev_auto_queue_empty'

tested with:
VERSION = 'BETA'
DATE = 'August 2017'
BEGIN = 2014
END = 2017

Seems to be related to HexRays removing an API from their IDP hook class

**Comment by demonduck** [comment]
moved to https://github.com/vrtadmin/FIRST-plugin-ida/issues/14
